name: Build and Publish Windows and macOS Python packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        architecture: [x64]
        python-version: [3.6, 3.7, 3.8]
        include:
          - os: windows-latest
            wheelname: win
          - os: macos-latest
            wheelname: macos

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        architecture: ${{ matrix.architecture }}
        python-version: ${{ matrix.python-version }}

    - name: Update Python pip, wheel, and twine
      run: |
        python -m pip install --upgrade pip wheel twine
      shell: bash

    - name: Build Python wheel
      run: |
        python -m pip wheel . -w wheelhouse
      shell: bash

    - name: Publish wheel to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        WHEEL_NAME: ${{ wheelname }}
      run: |
        python -m twine upload wheelhouse/*-${WHEEL_NAME}*.whl
      shell: bash
