name: Build and Publish source and wheels

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-10.15, ubuntu-20.04, windows-2019 ]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
        build_type: [Release]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        if: startsWith(matrix.os, 'macos')
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: anaconda-client-env
          channels: conda-forge,defaults
          mamba-version: "*"
      - if: startsWith(matrix.os, 'macos')
        shell: bash
        run: mamba install llvm-openmp==11.1.0
      - uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.architecture }}
          python-version: ${{ matrix.python-version }}
      - name: configure Python
        shell: bash
        run: |
          python -m pip install --upgrade pip numpy
          echo "pythonInterpreter=`which python`" >> $GITHUB_ENV
      - uses: g5t/make-test-action@v0
        with:
          flags: "-D Python3_EXECUTABLE=${{ env.pythonInterpreter }}"
          build: ${{ matrix.build_type }}

  windows:
    runs-on: windows-2019
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      fail-fast: true
      matrix:
        architecture: [x64]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.architecture }}
          python-version: ${{ matrix.python-version }}
      - uses: g5t/manywin-action@v0
        with:
          name: "windows-${{matrix.architecture}}-py${{matrix.python-version}}"

  macos:
    runs-on: macos-10.15
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      fail-fast: true
      matrix:
        architecture: [x64]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.architecture }}
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: anaconda-client-env
          channels: conda-forge,defaults
          mamba-version: "*"
      - shell: bash
        run: mamba install llvm-openmp==11.1.0
      - uses: g5t/manymac-action@v0
        with:
          name: "macos-${{matrix.architecture}}-py${{matrix.python-version}}"

  manylinux:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    strategy:
      fail-fast: true
      matrix:
        architecture: [x64]
        python-version: ['cp37-cp37m', 'cp38-cp38', 'cp39-cp39', 'cp310-cp310']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: ${{ matrix.architecture }}

      - name: Build manylinux python ${{ matrix.python-version }} wheel
        uses: RalfG/python-wheels-manylinux-build@v0.4.0-manylinux2010_x86_64
        with:
          python-versions: ${{ matrix.python-version }}
          build-requirements: 'cmake'
          system-packages: ''
          package-path: ''
          pip-wheel-args: '-w ./dist --no-deps'

      - name: Attach wheel to action
        uses: actions/upload-artifact@v2
        with:
          name: manylinux-${{matrix.architecture}}-${{ matrix.python-version }}
          path: dist/*manylinux*.whl

  source:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Update Python dependencies
        run: python -m pip install --upgrade pip setuptools
        shell: bash

      - name: Build source tarball
        run: python setup.py sdist
        shell: bash

      - name: Attach tarball to action
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: dist/*.tar.gz

  collect-artifacts:
    runs-on: ubuntu-latest
    needs: [source, manylinux, windows, macos]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          path: artifacts

      - name: Move artifacts into a single folder
        run : |
          mkdir dist
          find ${{ steps.download.outputs.download-path }} -type f -regex ".*\.\(tar\.gz\|whl\)" -exec mv {} dist/. \;

      - name: Attach artifacts to GitHub tagged release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/*.whl,dist/*.tar.gz"

      - name: Publish artifacts to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}