name: Sphinx

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    name: Build documentation with Sphinx in a Docker container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: repository
    #
    # - name: Checkout gh-pages
    #   uses: actions/checkout@v2
    #   with:
    #     ref: gh-pages
    #     path: pages

    - name: Checkout brille.github.io repository
      uses: actions/checkout@v2
      with:
        repository: brille/brille.github.io
        token: ${{ secrets.BRILLE_GITHUB_IO_TOKEN }}
        path: io

    - name: Sphinx Docker build
      uses: ./repository/.github/actions/build_sphinx
      with:
        source_dir: repository
        # pages_dir: "pages io"
        pages_dir: io
        is_release: ${{ contains(github.event_name, 'release') }}
        create_readme: true
