# adapted from https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/
name: CMake Build and Test Matrix

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
        build_type: [Release]

    steps:
    - name: (macOS) Install OpenMP
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install libomp

#    - name: Install HDF5 development files (Ubuntu)
#      run: sudo apt-get install libhdf5-dev
#      if: startsWith(matrix.os, 'ubuntu')
#
#    - name: Install HDF5 (Windows)
#      run: choco install hdf5
#      if: startsWith(matrix.os, 'windows')
#
#    - name: Install OpenMP & HDF5 (macOS)
#      run: brew install libomp hdf5
#      if: startsWith(matrix.os, 'macos')

    - uses: actions/checkout@v2

    - name: Setup Python for testing
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Update pip and install numpy for tests
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy

    - name: Configure CMake
      run: |
        cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)
        execute_process(
          COMMAND ctest -j ${N} -C ${{ matrix.build_type }} --output-on-failure
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()
