name: C/C++ CI

on: [push]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: install pybind11
      run: sudo apt install -y pybind11-dev
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

  # build-windows:
  #
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-latest, windows-2016]
  #
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: configure
  #     run: mkdir build && cd build && cmake ..
  #   - name: build
  #     run: cmake --build build
  #   - name: test
  #     run: cd build && ctest
