name: Main

on:
  push:
  pull_request:

concurrency :
  group: "${{ github.workflow }}-${{ github.ref == 'refs/head/main' && github.run_number || github.ref }}"
  cancel-in-progress: true

jobs:
  cmake_and_ctest:
    name: "CMake & CTest, ${{ matrix.variant.os }}, py${{ matrix.python-version }}"
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - { os: ubuntu-22.04} # current Ubuntu latest
          - { os: macos-12}
          - { os: macos-13}
          - { os: macos-14}
          - { os: windows-2022} # current Windows latest
        python-version: ["3.10"]
        cmake-type: ['Release']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install setuptools_scm conan numpy
      - run: echo "pythonInterpreter=`which python`" >> $GITHUB_ENV
      - name: configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.cmake-type }} -D Python3_EXECUTABLE=${{ env.pythonInterpreter }}
      - name: build
        run: cmake --build build --config ${{ matrix.cmake-type }} -j
      - name: test
        working-directory: build
        run: ctest -C ${{ matrix.cmake-type }} --output-on-failure -j
