name: Main

on:
  push:
  pull_request:

concurrency :
  group: "${{ github.workflow }}-${{ github.ref == 'refs/head/main' && github.run_number || github.ref }}"
  cancel-in-progress: true

jobs:
  cmake_and_ctest:
    name: "CMake & CTest, ${{ matrix.variant.os }}, py${{ matrix.python-version }}"
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - {os: ubuntu-22.04, cmake-preset: gha-test-ubuntu }
          - {os: macos-12, cmake-preset: gha-test-macos }
          - {os: windows-2022, cmake-preset: gha-test-windows }
        python-version: ["3.10"]
        cmake-type: ['Release']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup micromamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/config/${{ matrix.variant.cmake-preset }}.yml
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
      - run: echo "pythonInterpreter=`which python`" >> $GITHUB_ENV
      - name: configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.cmake-type }} -D PYTHON3_EXECUTABLE=${{ env.pythonInterpreter }}
      - name: build
        run: cmake --build build --config ${{ matrix.cmake-type }} -j
      - name: test
        working-directory: build
        run: ctest -C ${{ matrix.cmake-type }} --output-on-failure -j
