name: Main

on:
  push:
  pull_request:

concurrency :
  group: ${{ github.workflow }}-${{ github.ref == 'refs/head/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  cmake_and_ctest:
    name: CMake & CTest, ${{ matrix.variant.os }}, py${{ matrix.python-version }}
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - {os: ubuntu-20.04, cmake-preset: gha-test-ubuntu }
          - {os: macos-11, cmake-preset: gha-test-macos }
          - {os: windows-2019, cmake-preset: gha-test-windows }
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ilammy/msvc-dev-cmd@v1  # setup MSVC + Ninja
      - name: Setup micromamba environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: 0.23.0
          environment-file: .github/config/${{ matrix.variant.cmake-preset }}.yml
          cache-env: true
          extra-specs: python=${{ matrix.python-version }}
      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2.2
        with:
          key: ${{ matrix.variant.os }}

      - name: Cache Conan setup
        id: conan-cache-key
        run: |
          echo "::set-output name=key::$(/bin/date -u "+%Y%m%d")"
          echo "::set-output name=path::$(conan config home)"
      - name: Cache Conan
        uses: actions/cache@v1
        with:
          path: ${{ steps.conan-cache-key.outputs.path }}
          key: conan-${{ matrix.variant.os }}-${{ steps.conan-cache-key.outputs.key }}

      - run: cmake --preset ${{ matrix.variant.cmake-preset }}
      - run: cmake --build --preset build
      - run: ctest --preset test

